### ISSUE TITLE
Ideas on using stubs alongside other google packages

### ISSUE THREAD

**Issue by j-walker23** [henribru/google-ads-stubs#1]
Hello, me again.
These stubs have been awesome. Thanks again.

A little while ago I noticed PyCharm complains about missing imports in other, non ads, google packages. Guessing due to their namespacing pattern of having completely separate pypi packages install in the same `google/` folder.

As a workaround, I've just been uninstalling these stubs when doing non ads related work. Which works no problem, so this isn't anything important.

I was just curious if you knew any workarounds to make these coexist.

<img width="487" alt="Screen Shot 2020-02-15 at 8 49 59 PM" src="https://user-images.githubusercontent.com/2018885/74598825-04f76680-5036-11ea-8cbb-37066da4be91.png">

**Comment by henribru** [comment]
Sorry for the slow reply, I hadn't enabled notifications for new issues.

Unless Mypy also complains about these imports (please check this), I suspect this is actually a bug in PyCharm. The package includes a `py.typed` file with the word "partial" in it, which [PEP561](https://www.python.org/dev/peps/pep-0561/) defines as a way of specifying that a stub package doesn't contain full type annotations. It sounds like PyCharm is ignoring this and expecting my stubs to cover all packages under `google`, so when they don't, it thinks `ads` is the only thing it contains. I suggest you send a bug report to JetBrains about this. I can do so myself instead if you prefer, but I can't promise it will happen this weekend.

On an unrelated note, sorry that there haven't been any updates to the package, I've been very busy. I'm working on it though.

**Comment by j-walker23** [comment]
That makes perfect sense. I did notice the `partial` and then thought wtf, thats probably for this exact thing.

I'll def check with PyCharm. They seem to be painfully slow with many typing features.

Thanks again for the reply, this package has been extremely helpful!
